// <auto-generated />
using InvoiceCommon.Invoice.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace InvoiceCommon.Migrations
{
    [DbContext(typeof(InvoiceContext))]
    [Migration("20180519160550_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InvoiceCommon.Invoice.Persistence.ViewModels.InvoiceToProcessDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Rfc");

                    b.Property<string>("SocialReazon");

                    b.HasKey("Id");

                    b.ToTable("InvoicesToProcess");
                });

            modelBuilder.Entity("InvoiceCommon.Invoice.Persistence.ViewModels.InvoiceToProcessDetailDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("InvoiceToProcessDbId");

                    b.Property<string>("MeasureUnit");

                    b.Property<decimal>("Quantity");

                    b.Property<decimal>("UnitValue");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceToProcessDbId");

                    b.ToTable("InvoicesDetailsToProcess");
                });

            modelBuilder.Entity("InvoiceCommon.Invoice.Persistence.ViewModels.InvoiceToProcessDetailDb", b =>
                {
                    b.HasOne("InvoiceCommon.Invoice.Persistence.ViewModels.InvoiceToProcessDb")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceToProcessDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
